version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
#      - MYSQL_USER=blog # 直接使用root
#      - MYSQL_PASSWORD=blog

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
#      - ./web/staticfiles:/django_static # 如果只挂载没有生成后的静态文件夹 那生成的静态文件根本没有被nginx处理
      - ./web/collectedstatic:/django_static
      - ./nginx/ssl:/etc/nginx
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always

  web:
    build: .
    # command: python manage.py runserver 0:8000
    # ports:
    #   - "8000:8000"
    command: uwsgi --ini uwsgi.ini
    working_dir: /data/web
    volumes:
      - ./web:/data/web
    expose:
      - "8000"
    depends_on:
      - mysql
      - redis

  celery:
    build: .
    command: celery -A web worker -l info
    working_dir: /data/web
    volumes:
      - .:/data
    depends_on:
      - mysql
      - redis